version: '3'

volumes:
  local_postgres_data:
  odoo-web-data:

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfile
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8071:8071"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./local-addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
